mainRpcProxy:
  image: kumavis/eth-rpc-wrapper
  restart: always
  environment:
    VIRTUAL_HOST: "rpc.metamask.io"
    VIRTUAL_PORT: "9000"
    PORT: "9000"
    RPC_NODE: "http://mainEthNode:9000"
  ports:
    - "9000"
  links:
    - mainEthNode

testRpcProxy:
  image: kumavis/eth-rpc-wrapper
  restart: always
  environment:
    VIRTUAL_HOST: "testrpc.metamask.io"
    VIRTUAL_PORT: "9000"
    PORT: "9000"
    RPC_NODE: "http://testEthNode:9000"
  ports:
    - "9000"
  links:
    - testEthNode

mainEthNode:
  image: ethereum/client-go
  command: "--rpc --rpcaddr '0.0.0.0' --rpcport '9000' "
  restart: always
  environment:
    VIRTUAL_HOST: "rawrpc.metamask.io"
    VIRTUAL_PORT: "9000"
  volumes:
    - /var/data/geth:/root/.ethereum
  ports:
    - "9000"

testEthNode:
  image: ethereum/client-go
  command: "--rpc --rpcaddr '0.0.0.0' --rpcport '9000' --testnet --mine --minerthreads '1' --etherbase '0x18a3462427bcc9133bb46e88bcbe39cd7ef0e761'"
  restart: always
  environment:
    VIRTUAL_HOST: "rawtestrpc.metamask.io"
    VIRTUAL_PORT: "9000"
  volumes:
    - /var/data/geth:/root/.ethereum
  ports:
    - "9000"